### PR TITLE
added photos for wiki

### PR DESCRIPTION
**Pull request by xpd259**
Hello,
I hope you don't mind but I've been busy updating your wiki
with the old sites data before google delete it all.

this pull request is to add photos so they can be added to the X-Plane 
wiki page

regards
Dick Thomas

### CODE REVIEW

**Comment by uglyDwarf** [comment]
Hi,
of course I don't mind, on the contrary... Just one thing - I think that it is not necessary to copy the pictures, as all of them should be already in the src/qt_gui/help directory (I use them in the ltr_gui's help)...

Kind regards,

Michal

**Comment by xpd259** [comment]
Cool  I will check there 

also how would I build the software with wine support? (sorry for 2nd Question)

**Comment by uglyDwarf** [comment]
No problem... You are going to need wine development package (to get the headers and winegcc/wineg++), plus the nsis (nullsoft installer)...

And the config I use is:

./configure --prefix=/tmp/ltr --with-xplane-sdk=/home/sbuilder/devel/SDK/CHeaders --with-wine-libs=-L/usr/lib/i386-linux-gnu -L/usr/lib/i386-linux-gnu/wine

Hope it helps, if not just chime in and I'll help...

Kind regards,

Michal

**Comment by xpd259** [comment]
Thanks I couldn't find it on the old site I wanted to document it for people
I'm also trying to package some fedora builds using open build service

I'll close this and open another if I need help

**Pull request closed without merging**
